{{- if .Values.backup.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "kymacraft.fullname" . }}-backup
  labels:
    app: {{ template "kymacraft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  schedule: "{{ .Values.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            sidecar.istio.io/inject: "false"
        spec:
          securityContext:
            runAsUser: 1000
            fsGroup: 2000
          restartPolicy: OnFailure
          volumes:
          - name: cache
            emptyDir: {}
          - name: user
            emptyDir: {}
          - name: datadir
            persistentVolumeClaim:
              claimName: {{ template "minecraft.fullname" .Subcharts.minecraft }}-datadir
          - name: sshkey
            secret:
              secretName: {{ template "kymacraft.fullname" . }}-backup
          containers:
          - name: backup
            image: "{{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag }}"
            imagePullPolicy: IfNotPresent
            env:
            - name: GITHUB_REPO
              value: "{{ .Values.backup.githubRepo }}"
            volumeMounts:
            - mountPath: /data
              name: datadir
            - mountPath: /cache
              name: cache
            - mountPath: /cache/sshkey
              name: sshkey
            command:
            - /bin/sh
            - -ec
            - |
                echo "starting ssh-agent"
                eval "$(ssh-agent -s)"
                git config --global user.email "bot@kymacraft.com"
                git config --global user.name "kymacraftbot"

                mkdir ~/.ssh
                cat /cache/sshkey/ssh-key-github > ~/.ssh/ssh-key-github
                chmod 600 ~/.ssh/ssh-key-github
                
                echo ""
                echo "adding ssh key..."
                bash -c 'ssh-add ~/.ssh/ssh-key-github'
                ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

                echo ""
                echo "clone repo..."
                rm -rf /cache/repo
                mkdir /cache/repo
                git clone $GITHUB_REPO /cache/repo

                echo ""
                echo "preparing repo for new data..."
                cd /cache/repo
                rm -rf *

                echo ""
                echo "copying world..."
                cp -r /data/FeedTheBeast/world ./world

                echo ""
                echo "copying config..."
                cp /data/FeedTheBeast//usernamecache.json ./usernamecache.json
                cp /data/FeedTheBeast/whitelist.json ./whitelist.json
                cp /data/FeedTheBeast/usercache.json ./usercache.json
                cp /data/FeedTheBeast/user_jvm_args.txt ./user_jvm_args.txt
                cp /data/FeedTheBeast/server.properties ./server.properties
                cp /data/FeedTheBeast/ops.json ./ops.json
                cp /data/FeedTheBeast/banned-players.json ./banned-players.json
                cp /data/FeedTheBeast/banned-ips.json ./banned-ips.json
                cp -r /data/FeedTheBeast/logs ./logs

                echo ""
                echo "pushing changes..."
                git add .
                export TIMESTAMP=$(date +%Y-%m-%d/%H-%M-%S)

                git commit --allow-empty -m "$TIMESTAMP"
                git push origin main

                git tag $TIMESTAMP
                git push origin $TIMESTAMP
                
                echo ""
                echo "DONE"
{{- end -}}
