{{- if .Values.backup.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kymacraft.fullname" . }}-backup
  labels:
    app: {{ template "kymacraft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  ssh-key-github: "{{ .Values.backup.sshKey }}"
type: Opaque
{{- end -}}
