gateway:
  enable: true
  shootDomain: "kyma.cluster.local"

backup:
  enable: false
  image:
    repository: pprecel/kymacraft-helper
    tag: "0.2.2"
  schedule: "0 */2 * * *" # every 2h
  githubRepo:
  sshKey:

minecraft:
  image:
    repository: itzg/minecraft-server
    tag: "java17"

  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 20
    failureThreshold: 40
    successThreshold: 1
    timeoutSeconds: 4
  readinessProbe:
    initialDelaySeconds: 120
    periodSeconds: 20
    failureThreshold: 40
    successThreshold: 1
    timeoutSeconds: 4
  startupProbe:
    enabled: false
    failureThreshold: 30
    periodSeconds: 10

  resources:
      requests:
        memory: 4000M
        cpu: 500m
      limits:
        memory: 10000M
        cpu: 1500m

  minecraftServer:
    enabled: true
    eula: false
    servicePort: 25565
    difficulty: normal
    motd: "Welcome to Kymacraft Server!"

    type: "CURSEFORGE"
    cfServerMod: "https://media.forgecdn.net/files/4001/108/Kymacraft-Server-1.1.0.zip"

  persistence:
    dataDir:
      Size: 5Gi
      enabled: true
