gateway:
  enable: true
  shootDomain: "kyma.cluster.local"

backup:
  enable: false
  image:
    repository: pprecel/kymacraft-helper
    tag: "0.1.1"
  schedule: "0 */2 * * *" # every 2h
  modpackName: Kymacraft-Forge-Server-0.1.0
  githubRepo:
  sshKey:
  
minecraft:
  image:
    repository: itzg/minecraft-server
    tag: "java17"

  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 20
    successThreshold: 1
    timeoutSeconds: 2
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 20
    successThreshold: 1
    timeoutSeconds: 2
  startupProbe:
    enabled: false
    failureThreshold: 30
    periodSeconds: 10

  resources:
      requests:
        memory: 4000M
        cpu: 500m

  extraVolumes:
  - volumeMounts:
    - name: modpack
      mountPath: /modpack
    volumes:
    - name: modpack
      emptyDir: {}

  initContainers:
  - name: fetch-modpack
    image: pprecel/kymacraft-init:0.1.2
    resources:
      requests:
        memory: 4000M
        cpu: 500m
    volumeMounts:
    - name: datadir
      mountPath: /data
    - name: modpack
      mountPath: /modpack
    command: 
    - sh
    - -ec
    - |
      echo "init-container start..."
      cd /tmp
      git clone https://github.com/pPrecel/kymacraft-server
      cd kymacraft-server
      git lfs fetch
      git lfs checkout

      cp modpack/Kymacraft-Forge-Server-0.1.0.zip /modpack/Kymacraft-Forge-Server-0.1.0.zip
      echo "modpacks cloned"

  minecraftServer:
    enabled: true
    eula: false
    servicePort: 25565
    difficulty: normal

    type: "CURSEFORGE"
    cfServerMod: "/modpack/Kymacraft-Forge-Server-0.1.0.zip"
    rcon:
      password: "CHANGEMEPLS!!!"

  persistence:
    dataDir:
      enabled: true
